spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workpermit?useSSL=false&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false

server:
  port: 8080
